In [2]:

from PIL import Image
imageFile = "C:/Users/Chandu/Desktop/Capture.png"
im1 = Image.open(imageFile).convert('L')
# adjust width and height to your needs
width = 8
height = 8
im5 = im1.resize((width, height), Image.ANTIALIAS) 
import numpy as np
y=np.asarray(im5.getdata(),dtype=np.float64).reshape((im5.size[1],im5.size[0]))
#y=np.asarray(y,dtype=np.uint8)
y = np.subtract(255,y)
print(y)

In [21]:
im5.show()

In [4]:
pix_val = list(im5.getdata())
print(pix_val)

[255, 255, 249, 242, 245, 252, 255, 255, 255, 253, 244, 254, 246, 245, 255, 255, 255, 253, 244, 255, 246, 250, 255, 255, 255, 255, 248, 238, 242, 255, 255, 255, 255, 255, 250, 241, 243, 251, 255, 255, 255, 255, 243, 255, 252, 247, 255, 255, 255, 255, 248, 247, 248, 248, 255, 255, 255, 255, 255, 247, 246, 254, 255, 255]


[[ 0.  0.  6. 13. 10.  3.  0.  0.]
 [ 0.  2. 11.  1.  9. 10.  0.  0.]
 [ 0.  2. 11.  0.  9.  5.  0.  0.]
 [ 0.  0.  7. 17. 13.  0.  0.  0.]
 [ 0.  0.  5. 14. 12.  4.  0.  0.]
 [ 0.  0. 12.  0.  3.  8.  0.  0.]
 [ 0.  0.  7.  8.  7.  7.  0.  0.]
 [ 0.  0.  0.  8.  9.  1.  0.  0.]]


In [ ]:
im5.save('greyscale.png')