In [10]:

from PIL import Image
imageFile = "C:/Users/Chandu/Desktop/my-digit.png"
im1 = Image.open(imageFile).convert('L')
# adjust width and height to your needs
width = 8
height = 8
im5 = im1.resize((width, height), Image.ANTIALIAS) 
import numpy as np
y=np.asarray(im5.getdata(),dtype=np.float64).reshape((im5.size[1],im5.size[0]))
#y=np.asarray(y,dtype=np.uint8)
y = np.subtract(255,y)
print(y)

[[ 0.  0.  0.  3.  4.  1.  0.  0.]
 [ 0.  1. 17. 15. 11. 36. 12.  0.]
 [ 0. 13. 27.  2.  3. 44. 25.  0.]
 [ 0.  2. 10. 14. 12. 18. 24.  0.]
 [ 0.  0.  0.  0.  0.  0. 26.  3.]
 [ 0.  0.  0.  0.  1.  1. 20. 17.]
 [ 0.  0.  0.  0.  0.  0.  4. 11.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
